### ISSUE TITLE
Error while refreshing pending block on main: strconv.ParseUint: parsing "": invalid syntax

### ISSUE THREAD

**Issue by iRespectrum** [sammy007/open-ethereum-pool#362]
#### System information

Parity/v1.11.7-stable-085035f-20180717/x86_64-linux-gnu/rustc1.27.1

Redis version: Redis server v=4.0.10 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=861c87e1c67fd396

OS & Version: Ubuntu 16.04

Commit branch and hash: (`master`, `ba60e1c`)

2018/07/26 13:48:03 Can't parse pending block number
2018/07/26 13:48:03 Error while refreshing pending block on main: strconv.ParseUint: parsing "": invalid syntax

**Comment by mikeyb** [comment]
Try searching issues before posting duplicates.  This was already addressed months ago

**Comment by iRespectrum** [comment]
curl -X POST -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","method":"eth_getWork","params":[],"id":1}' http://127.0.0.1:8545

{"jsonrpc":"2.0","result":["0x823a9bc4790d16337832ac72847b9abfb42ecbf157fd2b9f03fe9f8b5e625d25","0x0565d880e378b22250f35f260bac49983734114a9d338b7d7bacea1985c67dd4","0x00000000000014d2ca992a1d6a3a4b1b110715dc6590be94cec95da6f064c356","0x5c116c"],"id":1}

Parity work

Ethereum main net

But the pool can not connect to the RPC

**Comment by atlanticcrypto** [comment]
@iRespectrum you need to pull the develop branch - parity 1.11 changed their json rpc conventions (removing the response the pool used for pending block height). it was fixed in the develop branch to use the getwork function instead.

@mikeyb just stop.

**Comment by mikeyb** [comment]
@atlanticcrypto just stop using logic?  Let the world of idiocy take over?  Nah, you do you, I will do me.  Keep my name out your mouth

**Comment by iRespectrum** [comment]
@atlanticcrypto use the branch to develop. There in the last commit the problem is solved

**Comment by mikeyb** [comment]
close issue

**Comment by parkhanju** [comment]
@iRespectrum 
I have the same problem.
Can you explain to me in more detail how you solved the problem?
I didn't understand the above contents.

**Comment by parkhanju** [comment]
@atlanticcrypto @iRespectrum 
I have the same problem.
What is the difference between master branch and develop branch?
The code is the same.

**Comment by stone212** [comment]
@iRespectrum @atlanticcrypto Did this work for you?  I pulled the develop branch (with `git pull origin develop`) and I still have the same error.  I am running Parity stable 1.11.8 on Ubuntu.  Maybe I did not pull correctly?  It seemed smooth so I did not try to debug the pull.

Maybe 1.11.8 has new problems?

My pull looked god:

``
$ git pull origin develop
From https://github.com/sammy007/open-ethereum-pool
 * branch            develop    -> FETCH_HEAD
Updating bcfc0eb..154ebf0
Fast-forward
 README.md           | 28 +++++++++++++---------------
 payouts/unlocker.go |  4 ++--
 proxy/blocks.go     | 44 ++++++++++++--------------------------------
 rpc/rpc.go          |  4 ++--
 4 files changed, 29 insertions(+), 51 deletions(-)
```

**Comment by atlanticcrypto** [comment]
We run 1.11.8 on our OEP with no problems. 

Shouldn't matter but try it with

git clone --branch develop

**Comment by stone212** [comment]
Yes a fresh pull worked.  Strange.

**Comment by iRespectrum** [comment]
@stone212 @atlanticcrypto 
Parity 2 work with **develop** branch
Parity 1 work with **master** branch
Geth work with **master** branch
